[package]
name = "lsm303dlhc-ng"
version = "0.3.4"
authors = ["Markus Mayer <widemeadows@gmail.com>", "Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A platform agnostic driver to interface with the LSM303DLHC (accelerometer + compass)"
keywords = ["embedded-hal-driver", "accelerometer", "compass", "MEMS", "IMU"]
license = "EUPL-1.2 OR MIT OR Apache-2.0"
homepage = "https://github.com/sunsided/lsm303dlhc"
repository = "https://github.com/sunsided/lsm303dlhc"
edition = "2021"
rust-version = "1.64"

[features]
default = ["accelerometer"]
accelerometer = ["dep:accelerometer"]
defmt = ["dep:defmt", "lsm303dlhc-registers/defmt"]

[dependencies]
accelerometer = { git = "https://github.com/rust-embedded-community/accelerometer.rs.git", rev = "0b61975", optional = true }
bitfield-struct = "0.12.1"
cast = { version = "0.3.0", default-features = false }
defmt = { version = "1.0.1", optional = true }
embedded-hal = "1.0.0"
generic-array = "1.0.0"
lsm303dlhc-registers = "0.1.4"

[dev-dependencies]
test-format = "0.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
